services:
  - type: web
    name: parker-card-audit-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: parker-audit-db
          property: connectionString
